language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: python manage.py test
before_deploy:
  - echo $AWS_ACCESS_KEY_ID
  - echo $AWS_SECRET_ACCESS_KEY
  - python -c "import os;print os.environ['AWS_ACCESS_KEY_ID']"
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    branch: master
    repo: MauricioDinki/forms-django
  bucket: django-forms
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: django-forms
  key: latest.zip
  bundle_type: zip
  application: DjangoForms
  deployment_group: DjangoFormsGroup
  region: us-west-2
  on: *2
after_deploy:
  - echo "Performing after deploy procedures..."
